export const ErrorCodes = {
  INVALID_MESSAGE: "INVALID_MESSAGE",
  RATE_LIMITED: "RATE_LIMITED",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_POSITION: "INVALID_POSITION",
  SPEED_HACK_DETECTED: "SPEED_HACK_DETECTED",
  SKILL_ON_COOLDOWN: "SKILL_ON_COOLDOWN",
  OUT_OF_RANGE: "OUT_OF_RANGE",
  INSUFFICIENT_MP: "INSUFFICIENT_MP",
  INVALID_TARGET: "INVALID_TARGET",
  ZONE_NOT_FOUND: "ZONE_NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
